// Code generated by euler/gen. DO NOT EDIT.

package problems

import "reflect"

var Functions = map[string]reflect.Value{
	"Problem1": reflect.ValueOf(Problem1),
	"Problem10": reflect.ValueOf(Problem10),
	"Problem11": reflect.ValueOf(Problem11),
	"Problem12": reflect.ValueOf(Problem12),
	"Problem2": reflect.ValueOf(Problem2),
	"Problem3": reflect.ValueOf(Problem3),
	"Problem31": reflect.ValueOf(Problem31),
	"Problem4": reflect.ValueOf(Problem4),
	"Problem5": reflect.ValueOf(Problem5),
	"Problem6": reflect.ValueOf(Problem6),
	"Problem64": reflect.ValueOf(Problem64),
	"Problem66": reflect.ValueOf(Problem66),
	"Problem7": reflect.ValueOf(Problem7),
	"Problem76": reflect.ValueOf(Problem76),
	"Problem77": reflect.ValueOf(Problem77),
	"Problem8": reflect.ValueOf(Problem8),
	"Problem9": reflect.ValueOf(Problem9),
}

