// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package problems

import "reflect"

var Functions = map[string]reflect.Value{
	"Problem1": reflect.ValueOf(Problem1),
	"Problem10": reflect.ValueOf(Problem10),
	"Problem2": reflect.ValueOf(Problem2),
	"Problem3": reflect.ValueOf(Problem3),
	"Problem4": reflect.ValueOf(Problem4),
	"Problem5": reflect.ValueOf(Problem5),
	"Problem6": reflect.ValueOf(Problem6),
	"Problem7": reflect.ValueOf(Problem7),
	"Problem8": reflect.ValueOf(Problem8),
	"Problem9": reflect.ValueOf(Problem9),
}

